# Generated by Django 5.0.2 on 2024-02-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('date', models.DateField(null=True)),
                ('department', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=34)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
